import { Validator } from './validator';
export * as Messages from './messages';
import * as Rules from './rules';
import { Langs, ValidationRuleContract } from './contracts';
import * as config from "./config";
export { Validator, Rules };
export declare function configure(customConf: config.IConfig): void;
export declare function lang(lang: Langs): void;
export declare function extend(ruleName: string, ruleFunc: (args?: Array<string>) => ValidationRuleContract): void;
export declare function koa(): (ctx: any, next: any) => Promise<void>;
